import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Samurai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <nav className="navbar navbar-expand-lg bg-transparent  position-absolute left-right-0 " >
        <div className={` ${styles.cWidht} container pb-5`}>
        <Image className={styles.obfContain} src="/samurai-logo.png" alt="Vercel Logo" width={150} height={86} />
          <button className="navbar-toggler focusOutlineunset " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon">
            <i className="fa fa-bars fs-25 text-white focusOutlineunset"></i>
            </span>
          
          </button>
          <div className="collapse navbar-collapse text-center" id="navbarSupportedContent">
            <ul className="navbar-nav m-auto mb-2">
              <li className="nav-item">
                <a className="nav-link text-uppercase fw-Normal text-white fs-4" aria-current="page" href="#">About Us</a>
              </li>
              <li className="nav-item">
                <a className="nav-link text-uppercase fw-Normal text-white fs-4" aria-current="page" href="#">Team</a>
              </li>
              <li className="nav-item">
                <a className="nav-link text-uppercase fw-Normal text-white fs-4" aria-current="page" href="#">Roadmap</a>
              </li>
              <li className="nav-item">
                <a className="nav-link text-uppercase fw-Normal text-white fs-4" aria-current="page" href="#">Q & A</a>
              </li>
              
            </ul>
           <div className={styles.bgButton}>
           <a href='#' className={`${styles.topButton} btn btn-outline-primary text-uppercase text-white`}  >connect wallet</a>
           </div>
          </div>
        </div>
      </nav>
      <div className={`${styles.bgTop11}`} style={{paddingTop: "15%"}}>
        <div className={`${styles.cWidht} container pt-5`}>
          <div className={`${styles.displayGrid} ${styles.iconList} mb-5`}>
            <a className='text-center '>
            <i className='fa fa-facebook  '></i>
            </a>
            <a className='text-center'>
            <i className='fa fa-instagram '></i>
              </a>
              <a className='text-center'>
              <i className='fa fa-twitter  '></i>
              </a>
              <a className='text-center'>
              <i className='fab fa-discord  '></i>
              </a>

          
          
          
         
          </div>


          <div className='text-center'>
            <h4 className='text-uppercase lh-sm text-white fw-normal fs-4 text-shadow-md'>
              Partner with one of the world's largest retailers 
              to showase your brand and products. </h4>
            <div className=' mt-5'>
            <a href='#' className={`${styles.topButton} ${styles.bgButton} btn btn-outline-primary mx-3 fw-normal text-uppercase text-white`}>
              <i className='fab fa-discord me-2'></i>JOIN DISCORD
              </a>
            <a href='#' className={`${styles.topButton} ${styles.bgButton} btn btn-outline-primary mx-3 fw-normal text-uppercase text-white`} >
              <i className="fa fa-twitter me-2"></i>FOLLOW TWITTER
              </a>
            </div>
          </div>
        </div>
      </div>




     <div className={styles.bgBody1}>
      <div className={`${styles.cWidht} container`}>
       <div className='text-center py-5'>
       <h1 className='fw-normal fs-1 text-white animate__animated animate__jackInTheBox animate__slower'>ABOUT US</h1>
        <p className='text-uppercase lh-lg text-white fs-20 mx-md-20 fw-normal lh-lg'>ut also the leap into electronic typesetting, remaining essentially unchanged.
          It was popularised in the 1960s with the release of Letraset sheets containing
          ut also the leap into electronic typesetting, remaining essentially unchanged.
          It was popularised in the 1960s with the release of Letraset sheets containing</p>
        <a href='#' className={`${styles.topButton} ${styles.bgButton} btn btn-outline-primary mx-3 fw-normal text-uppercase text-white`}>READ MORE
        <i className="fa fa-chevron-down mx-2 text-white"></i>
        </a>
       </div>

       <div className='py-5'>
       <div className="ratio ratio-16x9 mb-5">
        <iframe src="https://www.youtube.com/embed/zpOULjyy-" title="YouTube video"></iframe>
      </div>
       </div>

          <div className='pb-5'>
            <h1 className={`${styles.animatedContent} text-center fw-normal fs-1 text-white mb-5 text-uppercase`}>ROAD MAP</h1>
            <div className="row text-center pb-5 d-none">
              <div className="col-lg-4 ">
                <p className='fw-normal fs-2 text-white text-uppercase lh-sm'>phase <br></br> 01</p>
              <Image className={styles.obfContain} src="/v-3.png" alt="Vercel Logo" width={250} height={300} />
              </div>
              <div className="col-lg-4">
              <p className='fw-normal fs-2 text-white text-uppercase lh-sm'>phase <br></br> 02</p>
              <Image className={styles.obfContain} src="/v-2.png" alt="Vercel Logo" width={250} height={300} />
              </div>
              <div className="col-lg-4">
              <p className='fw-normal fs-2 text-white text-uppercase lh-sm'>phase <br></br> 03</p>
              <Image className={styles.obfContain} src="/v-1.png" alt="Vercel Logo" width={250} height={300} />
              </div>
            </div>

            <div className="row text-center pb-5">
             
              <ul className="nav nav-pills justify-content-center flex-w-unset" id="pills-tab" role="tablist">
                <li className="nav-item me-3rem" role="presentation">
                  <button className={`${styles.tabFocus} nav-link active p-0 bg-transparent border-0`}  id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">
                  <p className='fw-normal fs-2 text-white text-uppercase lh-sm'>phase <br></br> 02</p>
                  <Image className={styles.obfContain} src="/v-3.png" alt="Vercel Logo" width={250} height={300} />
                  <img src='/cone.png' className='d-block text-center mx-auto cone h-40px' />
                  </button>
                </li>
                <li className="nav-item me-3rem" role="presentation">
                  <button className={`${styles.tabFocus}  nav-link p-0 bg-transparent border-0`} id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
                  <p className='fw-normal fs-2 text-white text-uppercase lh-sm'>phase <br></br> 01</p>
                  <Image className={styles.obfContain} src="/v-2.png" alt="Vercel Logo" width={250} height={300} />
                  <img src='/cone.png' className='d-block text-center mx-auto cone h-40px' />
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button className={`${styles.tabFocus}  nav-link p-0 bg-transparent border-0`} id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">
                  <p className='fw-normal fs-2 text-white text-uppercase lh-sm'>phase <br></br> 03</p>
                  <Image className={styles.obfContain} src="/v-1.png" alt="Vercel Logo" width={250} height={300} />
                  <img src='/cone.png' className='d-block text-center mx-auto cone h-40px' />
                  </button>
                </li>
              </ul>
              <div className="tab-content" id="pills-tabContent">
                <div className={` ${styles.bgTabContent}  tab-pane fade show active text-white text-center p-5`} id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book
                </div>
                <div className={` ${styles.bgTabContent}  tab-pane fade text-white  p-5`} id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">222222222222222</div>
                <div className={` ${styles.bgTabContent}  tab-pane fade text-white  p-5`} id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">33333333333</div>
              </div>
            </div>


          </div>


  
          <div className='py-5'>
          <h1 className='text-center fw-normal fs-1 text-white mb-5 text-uppercase'>Team member</h1>
          <div className= "col-lg-12 col-12 text-center">
          <div className='d-flex justify-content-center' style={{ justifyContent: 'flex-end'}}>
          <Image className={styles.obfContain}  src="/banner-05.png" alt="Vercel Logo" width={160} height={300} />
          <Image className={styles.obfContain} src="/banner-06.png" alt="Vercel Logo" width={170} height={300} />
          <Image className={styles.obfContain} src="/banner-03.png" alt="Vercel Logo" width={200} height={600} />
          <Image className={styles.obfContain} src="/banner-04.png" alt="Vercel Logo" width={200} height={300} />
          <Image className={styles.obfContain} src="/banner-02.png" alt="Vercel Logo" width={160} height={300} />

          </div>
          </div>

          </div>

          <div className='pb-5 mb-5'>
            <h1 className='text-center fs-1 fw-normal  text-white mb-5 text-uppercase'>Q & A</h1>
            <div className='col-lg-12 col-12'>
              <div className={`${styles.bgAccordin} accordin`} id="accordionExample">
                <div className="accordion-item">
                  <h2 className={`${styles.focusOutlineunset} accordion-header `} id="headingOne">
                    <button className={`${styles.focusOutlineunset} ${styles.accordionButton} accordion-button bg-transparent fw-normal fs-5 text-white`} type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      Accordion Item #1
                    </button>
                  </h2>
                  <div id="collapseOne" className="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div className="accordion-body text-white ">
                      This is the first item's accordion body.It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                    </div>
                  </div>
                </div>
                <div className="accordion-item">
                <h2 className={`${styles.focusOutlineunset} accordion-header `} id="headingOne">
                    <button className={`${styles.focusOutlineunset} ${styles.accordionButton} accordion-button bg-transparent fw-normal fs-5 text-white`} type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      Accordion Item #2
                    </button>
                  </h2>
                  <div id="collapseTwo" className="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                    <div className="accordion-body text-white">
                     This is the second item's accordion body.It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                    </div>
                  </div>
                </div>
                <div className="accordion-item">
                <h2 className={`${styles.focusOutlineunset} accordion-header `} id="headingOne">
                    <button className={`${styles.focusOutlineunset} ${styles.accordionButton} accordion-button bg-transparent fw-normal fs-5 text-white `} type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                      Accordion Item #3
                    </button>
                  </h2>
                  <div id="collapseThree" className="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                    <div className="accordion-body text-white">
                      This is the third item's accordion body.It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                    </div>
                  </div>
                </div>
                <div className="accordion-item">
                <h2 className={`${styles.focusOutlineunset} accordion-header `} id="headingOne">
                    <button className={`${styles.focusOutlineunset} ${styles.accordionButton} accordion-button bg-transparent fw-normal fs-5 text-white`} type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseThree">
                      Accordion Item #4
                    </button>
                  </h2>
                  <div id="collapseFour" className="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                    <div className="accordion-body text-white">
                      This is the third item's accordion body. It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <footer className='pb-5'>
            <div className='col-lg-12 col-12 text-center'>
              <Image className={styles.obfContain} src="/samurai-logo.png" alt="Vercel Logo" width={150} height={46} />
            </div>
            <nav className="navbar navbar-expand-lg bg-transparent">
              <div className={` ${styles.cWidht} container `}>
                <div className="collapse navbar-collapse text-center" id="navbarSupportedContent">
                  <ul className="navbar-nav m-auto mb-2 mb-lg-0">
                    <li className="nav-item">
                      <a className="nav-link text-uppercase fw-Normal text-white fs-6" aria-current="page" href="#">About Us</a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link text-uppercase fw-Normal text-white fs-6" aria-current="page" href="#">Team</a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link text-uppercase fw-Normal text-white fs-6" aria-current="page" href="#">Roadmap</a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link text-uppercase fw-Normal text-white fs-6" aria-current="page" href="#">Q & A</a>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>

            <p className='m-0 text-white text-center fs-14 fw-300 '>
            &copy; Copyright 2022 | All Rights Reserved | Powered By <a href='https://eliteblue.net/'>Eliteblue Technologies</a>
            </p>
          </footer>

      </div>

      </div>

     


      
    </div>
  )
}
